cerpus/Edlib

.editorconfig, docker-compose.yml, localSetup/projects/nginx/nginx-conf.d/contentauthor.conf, localSetup/projects/nginx/nginx-conf.d/doku.conf, localSetup/projects/nginx/nginx-conf.d/edlib-api.conf, localSetup/projects/nginx/nginx-conf.d/edlib-internal-apis.conf, localSetup/projects/nginx/nginx-conf.d/edlibfacade.conf, localSetup/projects/nginx/nginx-conf.d/kibana.conf, localSetup/projects/nginx/nginx-conf.d/licenseapi.conf, localSetup/projects/nginx/nginx-conf.d/metadataservice.conf, localSetup/projects/nginx/nginx-conf.d/nginxconfig.conf, localSetup/projects/nginx/nginx-conf.d/npm-components-storybook.conf, localSetup/projects/nginx/nginx-conf.d/re-recommender.conf, localSetup/projects/nginx/nginx-conf.d/versionapi.conf
This change allows nginx to resolve hostnames at runtime instead of relying on each service to be ready at startup.
=> resolve upstream DNS dynamically

SETUP.md, docker-compose.yml, localSetup/projects/nginx/entrypoint.sh, scripts/first-time-setup.sh, scripts/update-certs.sh
In the interest of creating a pure Docker-based setup, this change moves generation of TLS certificates to the nginx container's entrypoint script.
=> Generate certificates inside nginx container

sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/AdminConfig.php, sourcecode/apis/contentauthor/app/Libraries/H5P/EditorConfig.php
The `mix()` function returns objects, apparently. These are implicitly cast to string when rendered in a template, but in non-template contexts this is not necessarily the case. We fix the issue by casting non-template uses of `mix()` to string.
=> Cast non-template uses of mix() to string

.github/dependabot.yaml, sourcecode/apis/resources/package.json, sourcecode/apis/resources/yarn.lock
Newer versions of the elasticsearch client doesn't support elasticsearch in AWS
=> Ignore updates to es client

sourcecode/apis/contentauthor/Dockerfile
* Restores Composer cacheability
* Make the Mix stage cacheable
Building the various CA containers now takes less than a minute on my machine after the first build.
=> Fix more performance issues with docker-compose

sourcecode/apis/contentauthor/app/Util.php, sourcecode/apis/contentauthor/tests/Unit/UtilTest.php
Assuming this is the cause of #362.
* Annotate App\Util methods properly.
* Handle exception without response, actually throw JsonException upon invalid JSON.
* Test App\Util::handleEdlibNodeApiRequest.
=> Improve error handling in HTTP utility

docker-compose.yml
`cacert.pem` doesn't exist upon first time running Docker Compose. As a result, Docker creates and mounts an empty directory by the same name, preventing the nginx container from starting.
This PR fixes the issue by mounting the parent directory instead.
=> Fix generation of cacert.pem on fresh install

sourcecode/apis/license/database/migrations/2019_07_04_072351_create_cache_directory.php
Removes a misuse of database migrations to perform a one-time post-deploy action.
Not only is the approach misguided, the code would only work under a very narrow set of conditions due to not accounting for notices/warnings/errors being converted to exceptions. Upon running `docker-compose up`, `fileowner()` would fail, and the container wouldn't start. As the Docker setup ensures the storage director is set up, we can simply remove the migration code.
This should have no impact on existing environments, as they already have an entry in the migrations table.
=> Remove bad migration in licenseapi

sourcecode/apis/contentauthor/app/Logging/JsonFormatter.php, sourcecode/apis/contentauthor/config/logging.php
Brings back stack traces for JSON logs. Functions/methods and parameters are still missing, but better than nothing.
Before:
~~~json
{
"channel" : "local",
"context" : {
"exception" : {
"class" : "Exception",
"code" : 0,
"file" : "/app/app/Http/Controllers/Admin/AdminController.php:149",
"message" : "some message"
},
"userId" : 2
},
"datetime" : "2022-01-14T08:20:08.188890+00:00",
"extra" : {},
"level" : 400,
"level_name" : "ERROR",
"message" : "some message"
}
~~~
After:
~~~json
{
"channel" : "local",
"context" : {
"exception" : {
"class" : "Exception",
"code" : 0,
"file" : "/app/app/Http/Controllers/Admin/AdminController.php:149",
"message" : "some message",
"trace" : [
"/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54", …
=> Log stack traces in Content Author

sourcecode/apis/contentauthor/app/Libraries/H5P/Video/NDLAVideoAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Video/StreampsAdapter.php, sourcecode/apis/contentauthor/config/ndla-import.php
NDLAVideoAdapter and StreampsAdapter will create malformed URLs if passed null or empty string. This happens if `NDLA_H5P_VIDEO_ADAPTER_KEY` and related env variables are left unconfigured, which causes a cryptic cURL error to be raised.
To make the problem more obvious, the config values are defaulted to null, and the `string` type added to the config parameters in the adapters' constructors. In addition, the strings are checked for emptyness to ensure that a declared env variable left blank cannot result in a malformed URL.
=> Fail early upon missing config in video adapters

sourcecode/apis/common/Dockerfile
Lock to PHP 8.0.14 to avoid a build failure with ext-sockets.
=> Fix broken common API build

sourcecode/npm/components/.babelrc, sourcecode/npm/components/package.json, sourcecode/npm/components/yarn.lock
Removes `@babel/preset-env` so JSX is transformed to standard ES modules instead of being  mangled for running in web browsers. This allows for discovery of parameters through the IDE.
No breaking changes are expected, as the structure of `dist/` ends up being the same. The library was only consumed through Webpack, so it's of no concern that the pre-built files won't run in a browser.
=> Export @cerpus/edlib-components as ES modules

sourcecode/apis/contentauthor/app/Content.php
We are receiving messages in the resourceapi with the wrong data format:
```json
{
"externalSystemName": "contentAuthor",
"externalSystemId": "88753afb-ac86-4c11-b843-a1e913f8109d",
"title": "asdf",
"ownerId": "1",
"isListed": false,
"isPublished": false,
"language": "eng",
"contentType": "article",
"license": "BY",
"maxScore": 0,
"createdAt": "2022-02-24T14:10:54.000000Z",
"updatedAt": "2022-02-24T14:10:54.000000Z",
"emailCollaborators": {
"2": "max+2@cerpus.com",
"1": "max@cerpus.com"
},
"collaborators": [],
"authorOverwrite": null
}
```
`emailCollaborators` should have been an array. This PR fixes the source of this problem
=> Wrong message format in pubsub

sourcecode/apis/resources/src/constants/licenses.js, sourcecode/apis/resources/src/services/resource.js
Shared resources can not be edited if license is EDLL or CC with ND element
=> Issue #621: Remove shared resource edit capability if not allowed by license 

sourcecode/apis/contentauthor/app/Http/Middleware/EdlibParseJwt.php
Sometimes, after a session expiry(?), CA will attempt to access an undefined `roles` property in the JWT payload. This change fixes the problem.
=> Fix access to undefined roles property

sourcecode/apis/contentauthor/app/Exceptions/H5PValidationFailureException.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php
`App\Exceptions\H5PValidationFailureException` is created to represent the exception that presumably was meant to be caught here. This will result in the expected 422 status code when it bubbles up.
=> Remove try-catch in H5PController::store that masks a fatal exception

sourcecode/apis/contentauthor/app/Traits/Versionable.php
Versioning is *required* for publishing to work, but in the event it fails, it would do so silently. This should fix the problem.
=> Remove try/catch that silently breaks versioning

sourcecode/apis/contentauthor/app/Http/Controllers/QuestionSetController.php, sourcecode/apis/contentauthor/app/Http/Middleware/AddExtQuestionSetToRequestMiddleware.php, sourcecode/apis/contentauthor/app/Providers/AppServiceProvider.php, sourcecode/apis/contentauthor/tests/Http/Middleware/AddExtQuestionSetToRequestMiddlewareTest.php
Makes it possible to actually see what `AddExtQuestionSetToRequestMiddleware` is doing at a first glance.
=> Deobscurify and test ext_question_set middleware

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/AjaxRequest.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php, sourcecode/apis/contentauthor/resources/assets/js/admin.js, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/routes/admin.php
* Changes `Framework::deleteLibrary` to adhere strictly to the interface specification.
* Moves the `H5PCore::deleteLibrary` call to its own controller, away from the horror show in `App\Libraries\H5P\AjaxRequest`.
* Adds a check preventing the library from being deleted if it has associated resources (may or may not be related to #638)
=> Clean up h5p library deletion

sourcecode/apis/contentauthor/app/Libraries/H5P/Storage/H5PCerpusStorage.php
Fixes an issue where uploading certain .h5p files would result in an error such as:
~~~
Impossible to create the root directory "/tmp/h5p/temp/h5p-627103cd869c6/blob-1.0".
~~~
That `saveFileFromZip` is called for directories is probably a bug in the H5P core library.
=> Handle directory creation when uploading h5ps

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminController.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/AjaxRequest.php, sourcecode/apis/contentauthor/routes/web.php
1. Removes unused actions
* `content_upgrade_progress` (broken due to private method missing)
* `setProgress` (handled by progress controller)
* `contents_user_data` (handled by progress controller)
2. Split each action into its own method
3. Removes usage of `filter_var(INPUT_GET, ...)` in favour of using Laravel's requests
4. Throws HTTP exception objects
5. General cleanup until PHPStorm showed ✅
=> Refactor AjaxRequest

sourcecode/apis/contentauthor/Dockerfile
No longer included in latest Alpine. Let's get rid of it.
=> Remove dependency on Python 2

.github/workflows/api-contentauthor.yaml, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/Column.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/Dialogcards.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/DragQuestion.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/DragText.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/ImagePair.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/MemoryGame.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/MultiChoice.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/QuestionSet.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/Video.php, sourcecode/apis/contentauthor/app/Traits/ReturnToCore.php, sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/database/factories/FileFactory.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/phpstan.neon.dist
Adds a Github action that runs PHPStan with a generated baseline. Some of the errors couldn't be committed to the baseline, and those have been fixed in this PR so we get an error-free run.
Worth noting that PHPStorm will detect PHPStan and attempt using it automatically.
(Needs to be rebased on master once #1266 is merged)
=> Implement phpstan

localSetup/projects/nginx/nginx-conf.d/doku.conf, localSetup/projects/nginx/nginx-conf.d/edlib-api.conf, localSetup/projects/nginx/nginx-conf.d/edlib-internal-apis.conf, localSetup/projects/nginx/nginx-conf.d/npm-components-storybook.conf, localSetup/projects/nginx/nginx-conf.d/re-recommender.conf, localSetup/projects/nginx/nginx-conf.d/www.conf, sourcecode/apis/contentauthor/docker/contentAuthor.conf.template
For whatever reason, the local nginx instances had access logs disabled in many cases. This only serves to make debugging harder, so we re-enable them.
There were also a few instances of `access_log on` which actually causes logs to be output to /etc/nginx/on instead of re-enabling logging to the previous used path. These are removed, too.
=> Remove unhelpful disabling of access logs

CONTRIBUTING.md, sourcecode/docs/docs.edlib.com/docs/developers/contributing/contributing.mdx
* Remove information in CONTRIBUTING.md that's redundant with the documentation, direct readers to documentation instead.
* Fix strange reference to "Apache GPL"
=> Improvements to contribution docs

sourcecode/apis/common/Dockerfile
Fixes healthcheck, which relies on nginx's placeholder page.
=> common api: don't overwrite default nginx vhost

docker-compose.yml, localSetup/helpers/start-scripts/wait-for.sh, sourcecode/apis/auth/Dockerfile
Make authapi work on first startup.
Also fixes failing `wait-for-it.sh` (bash not present), and a failing build (that is ignored because of `;` instead of `&&`) caused by incorrect symlinking of the `python` binary.
=> fix authapi in docker setup

sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/H5PLibraryLibrary.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
H5PFrameworkInterface::loadLibrary requires that FALSE be returned if a library cannot be loaded, but our implementation in App\Libraries\H5P\Framework would assume the existence of a database entry, causing errors. This PR fixes that, and also replaces the use of PDO/SQL with much simpler use of Eloquent.
=> Fix H5PFrameworkInterface::loadLibrary

sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PImport.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PLibraryAdmin.php, sourcecode/apis/contentauthor/tests/Unit/Libraries/H5P/FrameworkTest.php
* Remove implementation-specific methods that could cause warnings about polymorphic calls.
* Turn `setInfoMessage`/`setErrorMessage` into adder methods (I think this was the interface's intention anyway, the methods are just named incorrectly)
* Make `getMessages` adhere to the interface.
=> Refactor handling of H5PFrameworkInterface messages

sourcecode/apis/contentauthor/app/Article.php, sourcecode/apis/contentauthor/app/H5PContent.php, sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/H5PLibraryCapability.php, sourcecode/apis/contentauthor/app/LibraryDescription.php, sourcecode/apis/contentauthor/app/Link.php, sourcecode/apis/contentauthor/app/Providers/AuthServiceProvider.php, sourcecode/apis/contentauthor/app/Providers/EventServiceProvider.php, sourcecode/apis/contentauthor/app/Traits/Collaboratable.php, sourcecode/apis/contentauthor/routes/admin.php, sourcecode/apis/contentauthor/routes/api.php, sourcecode/apis/contentauthor/routes/web.php
Use `::class` instead of strings with class names. This makes it easier to spot unused code, navigate around using PHPStorm, etc.
=> Use class literals

sourcecode/apis/contentauthor/app/Content.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/ArticleInfoController.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/GameInfoController.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/H5PInfoController.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/QuestionSetInfoController.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php, sourcecode/apis/contentauthor/database/factories/H5PContentFactory.php, sourcecode/apis/contentauthor/database/migrations/2022_07_27_080000_add_is_private_to_links_table.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/tests/Integration/Article/Handler/HandlePrivacyTest.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/API/Handler/ContentTypeHandlerTest.php
Make `App\Content::$is_private` a bool instead of using 0 and 1.
This also fixes an issue where $isPrivate initialised to null, which isn't valid for the column. Since the `links` table didn't have an `is_private` column, it was added so the `App\Link` model, which inherits from `App\Content`, works correctly.
=> use bool for Content::$is_private

sourcecode/apis/contentauthor/app/Article.php, sourcecode/apis/contentauthor/app/Http/Controllers/ArticleController.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/resources/views/article/show.blade.php, sourcecode/apis/contentauthor/tests/Integration/Article/ArticleTest.php
Adds an `App\Article::render()` intended to be used whenever an article is displayed to the end-user. Currently, this only rewrites article upload paths using a new approach.
The previous approach would leave dangling changes to the Article model, possibly leading to those being accidentally persisted somewhere down the line. Also, the use of `str_replace()` has been removed in favour of actually parsing the HTML to change only the `src` attributes.
=> Cleaner rewriting of cloud paths

docker-compose.yml, sourcecode/www/Dockerfile, sourcecode/www/docker-entrypoint-dev.sh
* Use Alpine instead of Debian-based image
* Don't lock to a particular minor version of the `node` image
* Handle certificates properly
* Let docker-compose.yml define the command that's run
=> fix misc issues with so-called www's docker setup

sourcecode/apis/contentauthor/config/h5p.php
`h5p.storage.publicPath` is used by H5P core as a prefix for some scripts. This breaks the URL for the upgrade script, so we just blank it out.
=> Fix upgrade script URL

sourcecode/apis/contentauthor/app/Libraries/H5P/LtiToH5PLanguage.php
Passing NULL to PHP's internal functions is [deprecated](https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg) and will stop working in PHP 9. In `LtiToH5PLanguage::convert`, the deprecation warning causes a test failure under very specific conditions (coverage with xdebug + pcov, running the entire suite).
=> Fix deprecated passing of null to php function

sourcecode/apis/resources/src/services/elasticSearch.js, sourcecode/apis/resources/src/services/resource.js
It turns out the view count is meant to be populated upon reindexing search, but the code was mistakenly accessing the `count` property on a number.
=> Proper fix for the view counts

docker-compose.yml, sourcecode/apis/auth/Dockerfile, sourcecode/apis/auth/docker-entrypoint-dev.sh, sourcecode/apis/auth/package.json, sourcecode/apis/auth/yarn.lock
The shell-based wait script would fail on authapi for some reason, so we replace it with the `wait-on` npm package.
=> Fix auth startup properly

docker-compose.yml, sourcecode/apis/contentauthor/Dockerfile
This also skips the redundant building of assets in the dev Docker image.
=> Watch CA assets for change in dev environment

.github/actions/awsDeploy/action.yaml, .github/workflows/api-contentauthor.yaml, .github/workflows/create-release.yaml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Replace deprecated set-output with env files

localSetup/projects/certs/generate-certs.sh
Makes it easier to access the dev environment in case you cannot or don't want to accept a self-signed root CA.
=> Use wildcard certificates, remove unused alt names

sourcecode/apis/contentauthor/app/Libraries/H5P/H5PLibraryAdmin.php, sourcecode/apis/contentauthor/resources/assets/sass/admin.scss, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-check.blade.php
- Cleanup HTML and remove excessive wrapping
- Align Action buttons
- Catch exceptions thrown by validator when uploading .h5p library
=> CA Admin H5P libraries cleanup and fixes

sourcecode/apis/contentauthor/app/Http/Controllers/API/TranslationController.php, sourcecode/apis/contentauthor/app/Http/Requests/ApiTranslationRequest.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Dataobjects/H5PTranslationDataObject.php, sourcecode/apis/contentauthor/app/Libraries/H5P/TranslationServices/NynorobotAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/TranslationServices/NynorskrobotenAdapter.php, sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/tests/Unit/Libraries/H5P/TranslationServices/NynorobotAdapterTest.php
Switch to using Nynorobot's HTML translation endpoint, as the endpoint in CA receives HTML input. To avoid multiple requests, each field becomes its own element in the HTML that is sent off to be translated, and the HTML response is then converted back into `path => value` array elements.
In a separate commit, request validation was added and some general cleanup was performed. It might be best to review these commits separately.
=> Use HTML translation endpoint for Nynorobot

sourcecode/apis/contentauthor/app/Console/Commands/RemoveOldContentLocks.php, sourcecode/apis/contentauthor/config/logging.php
Laravel has a logger implementing [PSR-3](https://www.php-fig.org/psr/psr-3/) which defines the `info` logging level as:
```php
/**
* Interesting events.
*
* Example: User logs in, SQL logs.
*
* @param string $message
* @param array $context
* @return void
*/
public function info($message, array $context = array());
```
Yet, Content Author logs with this level what is indisputably **not** an interesting event: that nothing happened. This happens every minute, filling the logs with useless information.
To fix this, the level is adjusted to `debug`, and the minimum logging level for the stderr handler is set to `info`.
=> Do not log uninteresting events

sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock
This updates to a version of cerpus/cerpushelper that doesn't result in a downgrade of guzzlehttp/promises.
=> Update Cerpus packages

sourcecode/apis/contentauthor/app/Libraries/H5P/H5PLibraryAdmin.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PLibraryAdminTest.php
`skipped` contains IDs of content that failed to update, it's used to filter already failed content from being sent to the client again
=> CA Admin: Improve bulk updating content by using new 'skipped' value

sourcecode/apis/contentauthor/app/Http/Middleware/LtiBehaviorSettings.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/Answer.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/BaseDataObject.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/BehaviorSettingsDataObject.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/EditorBehaviorSettingsDataObject.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/MultiChoiceQuestion.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/Question.php, sourcecode/apis/contentauthor/app/Libraries/DataObjects/Questionset.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Interfaces/ContentTypeInterface.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Packages/H5PBase.php, sourcecode/apis/contentauthor/app/Libraries/QuestionSet/QuestionSetConvert.php, sourcecode/apis/contentauthor/app/Traits/H5PBehaviorSettings.php, sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/API/Handler/ContentTypeHandlerTest.php, sourcecode/apis/contentauthor/tests/Integration/Traits/ImagePairTraitTest.php, sourcecode/apis/contentauthor/tests/Unit/Traits/H5PBehaviorSettingsTest.php
Core is long gone, but we still used data objects from its client library. To ease the maintenance burden, these are copied to CA and the client library removed.
=> Remove dependency to cerpus/coreclient

sourcecode/apis/contentauthor/resources/assets/react/theme/cerpusUI.js
Fixes `Failed prop type: Invalid prop 'elevation' of type 'string' supplied to 'ForwardRef(Paper)', expected 'number'` logged when loading editor
=> Fix 'Failed prop type' error loading editor

sourcecode/apis/auth/src/services/externalAuthAdatpers/helpers.js
More fixes for #2339
As an aside, we couldn't have spotted this during development since auth is bypassed in the local environment.
=> allow empty names in authapi

sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Jobs/ExportH5P.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/CerpusH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Audio/NDLAAudioBrowser.php, sourcecode/apis/contentauthor/app/Libraries/H5P/File/NDLATextTrack.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PExport.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Image/NDLAContentBrowser.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Interfaces/H5PAdapterInterface.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Interfaces/H5PExternalProviderInterface.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Traits/H5PCommonAdapterTrait.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Video/NDLAVideoAdapter.php, sourcecode/apis/contentauthor/app/Providers/H5PServiceProvider.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/phpstan.neon.dist, sourcecode/apis/contentauthor/public/js/h5p/ndla-contentbrowser.js, sourcecode/apis/contentauthor/stubs/h5p-core/H5PExport.stub, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PExportTest.php
This fixes exporting Brightcove videos. It is now possible to export such a video, and it will reference the video source and text tracks located in the .h5p file. You can then upload the .h5p again and the video will work in any H5P system (theoretically).
Some additional improvements were included:
* Unwanted HTML escaping in the exported H5P JSON data has been fixed. We use the so-called H5PValidator to resolve dependencies, and nothing else.
* The `H5PExport::generateExport()` method now uses config taken in constructor and the `H5PContent` object as a parameter, instead of the other way round. The method is also rewritten to be less of a roundabout to read.
* General improvements to method naming.
* Some improvements that aren't strictly related, but would have been included in a big …
=> Fix exporting Brightcove videos

sourcecode/apis/contentauthor/app/Http/Middleware/SignedOauth10Request.php, sourcecode/apis/contentauthor/app/Http/Requests/LTIRequest.php
The OAuth library expects parameters to be strings, but Laravel converts empty strings to null. This causes a type check to fail.
In the future, this should probably be handled by the Laravel package for edlib-resource-kit.
=> fix OAuth 1 null params

sourcecode/apis/contentauthor/app/Libraries/H5P/H5PConfigAbstract.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PViewConfig.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PViewConfigTest.php
In the view/edit/create config: 
- The value `false` for environment setting `h5p.saveFrequency` was not handled correctly
- `user` was always added
=> CA Config: Fix issue where 'h5p.saveFrequency' is false, don't add user by default

sourcecode/apis/contentauthor/app/Libraries/H5P/H5PViewConfig.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PViewConfigTest.php
The libraries required to view the content was set to late
=> GH #2382: Library dependencies for H5P content must be set earlier

sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/CerpusH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PConfigAbstract.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PCreateConfig.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PEditConfig.php, sourcecode/apis/contentauthor/phpunit.xml, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/H5PControllerTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PCreateConfigTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PEditConfigTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PViewConfigTest.php
- Add missing settings from adapter in create/edit H5P config
- Fix NDLA adapter accessing protected variable in H5P config
- Update unittests
=> GH #2385: Missing Wiris config caused CKEditor crash in create/edit NDLA mode

sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/phpstan.neon.dist, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PConfigAbstractTest.php
Adds the [phpstan-banned-code extension](https://packagist.org/packages/ekino/phpstan-banned-code) to prevent use of debug statements (`dd()`, `dump()`, `phpinfo()`, `var_dump()`), stuff that bypasses Laravel's output (`die`/`exit`, `echo`/`print`, `printf()`, `print_r()`), nasty surprises ([backtick operator](https://www.php.net/manual/en/language.operators.execution.php)), and use of test code outside of tests.
This is primarily intended to make sure we don't commit code containing `dd()` or such, as this is easy to do by accident if you don't use a debugger, and can leak details that should not be seen.
One test class was misnamed and triggered the test-code-outside-tests detection, so has been renamed. The other discovered issues are baselined.
=> Detect debug function calls and other undesirable statements

sourcecode/apis/contentauthor/config/filesystems.php
Fixes the URLs generated in #2441. Additionally, this requires a change to the CloudFront configuration.
=> Add CDN URL to s3 config

docker-compose.yml, localSetup/projects/nginx/templates/hub.conf.template, scripts/update-host-file.sh, sourcecode/hub/app/Http/Middleware/ContentSecurityPolicy.php, sourcecode/hub/package-lock.json, sourcecode/hub/vite.config.js
This enables hot module reloading (HMR) in Vite which allows the Edlib 3 hub to apply CSS changes, etc. on the fly without hitting reload.
Unfortunately, I was not able to reverse proxy the HMR server in a sensible fashion to allow assets to be served from https://hub.edlib.test, so this change requires a new /etc/hosts entry:
```
127.0.0.1  hub-vite-hmr.edlib.test
```
=> Enable hot module reloading for Vite in dev environment

sourcecode/apis/contentauthor/Dockerfile
Building CA test image fails with the error
```
#20 [frontend  3/11] RUN npm i -g npm node-gyp
#20 0.893 npm ERR! code EBADENGINE
#20 0.895 npm ERR! engine Unsupported engine
#20 0.896 npm ERR! engine Not compatible with your version of node/npm: npm@10.0.0
#20 0.897 npm ERR! notsup Not compatible with your version of node/npm: npm@10.0.0
#20 0.898 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
#20 0.898 npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
```
Attempt to fix by not installing/updating npm
=> Fix CA build

docker-compose.yml
MariaDB 11 Docker images no longer contain the mysql* binaries, breaking the healthcheck.
Although the MYSQL_* env variables still work, it seems likely they'll be removed too at some point, so these are also changed.
=> fix mariadb healthchecks

sourcecode/apis/contentauthor/resources/assets/react/components/H5pEditor/List/HtmlEditor.js, sourcecode/apis/contentauthor/resources/assets/react/components/H5pEditor/List/ListItem.js
- Changes to texts in script view was not applied
- For changed texts, instead of displaying the original text when focusing an editor in script view, the original text is now displayed when entering the script view.
=> GH #2500: CA: Fix issue with changes to texts in script view not applied

sourcecode/apis/contentauthor/app/H5PLibrariesHubCache.php, sourcecode/apis/contentauthor/app/H5PLibraryCapability.php, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/database/factories/H5PLibrariesHubCacheFactory.php, sourcecode/apis/contentauthor/database/factories/H5PLibraryCapabilityFactory.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/AjaxRequestTest.php
The icons for the H5P content types was missing when selecting a content type to create content for. This was probably caused by a merge conflict in `composer.lock` not being resolved correctly.
Added tests to verify content type listing.
=> Fix missing H5P content type icons caused by h5p-editor library downgrade. Add tests

sourcecode/proxies/lti/src/controllers/launch.js, sourcecode/proxies/lti/src/controllers/launchEditor.js, sourcecode/proxies/lti/src/controllers/lti.js, sourcecode/proxies/lti/src/services/lti.js
Caused by JWT handling being removed from CA, but user details not being sent as regular LTI params.
=> Fix missing H5P authorship

sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PViewConfig.php, sourcecode/apis/contentauthor/app/Lti/LtiRequest.php, sourcecode/apis/contentauthor/phpunit.xml, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/H5PControllerTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PViewConfigTest.php, sourcecode/proxies/lti/src/services/lti.js
Removes an HTTP request to resourceapi that is done before showing content. This is part of making CA independent of old Edlib and making it compatible with Edlib 3.
=> CA: get embed details from LTI params

sourcecode/apis/contentauthor/app/H5PLibraryLanguage.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminH5PDetailsController.php, sourcecode/apis/contentauthor/app/Http/Requests/AdminTranslationUpdateRequest.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-check.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/translation.blade.php, sourcecode/apis/contentauthor/routes/admin.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/Admin/AdminH5PDetailsControllerTest.php
Allow editing the existing translations stored in the database for H5P content types and libraries
=> GH #2589: CA Admin: Allow updating library translations in database

sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php
Revert last change to `admin/library-upgrade/index.blade.php`  to fix 500 error in CA admin
=> Fix 500 error on CA admin

sourcecode/apis/contentauthor/app/H5PContent.php, sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminH5PDetailsController.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/views/admin/fragments/dependency-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/content-details.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-check.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-content.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/translation.blade.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/Admin/AdminH5PDetailsControllerTest.php
- Fix error on content history if item in history was deleted from CA database
- Fix incorrect warning about semantics difference on content type check
- Show last updated for H5P Hub cache
- Show content type icon on content type details page
- Show content count on content type details page
- Highlight different patch-version in list instead of with error text on content type details page
- Show name of language on hover in content details page
- Show name of language on translation edit page
- Show version for libraries that can be installed from H5P.org hub
- Add link to content type from content details
- If resource is deleted display time of deletion
- Display status of content lock
=> CA Admin: Fix error on content history if content deleted from CA, incorrect error on content type semantics diff, other adjustments

sourcecode/apis/contentauthor/.env.example, sourcecode/apis/contentauthor/config/app.php, sourcecode/apis/contentauthor/config/cache.php, sourcecode/apis/contentauthor/config/database.php, sourcecode/apis/contentauthor/config/session.php, sourcecode/apis/contentauthor/database/factories/GameFactory.php, sourcecode/apis/contentauthor/phpunit.xml
Vapor uses Laravel's naming convention for database variables, e.g. `DB_HOST`, so CA needs to recognise these. The `EDLIBCOMMON_` stuff was misguided and should be removed after we shut down k8s, but CA will keep supporting them for now.
While we're at it, we do some minor cleanup to bring the configuration closer to the Laravel skeleton application's defaults.
=> use less non-standard laravel config

docker-compose.yml
Since the upgrade requires a clean data directory anyway, the bind mount is changed to be a volume, which performs better on Windows/macOS due to not requiring file sharing.
=> Upgrade Postgres from 11 -> 16 in dev

sourcecode/apis/contentauthor/app/H5PLibrary.php
The addons are loaded in the H5P Editor for content types that are hardcoded in H5P Editor,`h5peditor.class.php`, as having WYSIWYG editor, currently these are 'H5P.CoursePresentation', 'H5P.InteractiveVideo' and 'H5P.DragQuestion'. They are loaded for all libraries when viewing H5P.
Addons can be identified by checking if there is a `addTo` property in the H5P librarys `library.json` file. In the database this value is stored in the column `h5p_libraries.add_to`.
An example of an addon is the 'H5P.MathDisplay' library.
No documentation was found on the H5P.org site
=> H5P addons fails to load if having patch version in folder name

sourcecode/apis/contentauthor/resources/assets/react/components/H5pEditor/List/ListItem.js
Characters that are encoded are `& ' " < >`
=> GH #2662: Encode/decode special characters in CA script-view

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminUserController.php, sourcecode/apis/contentauthor/database/migrations/2014_10_12_104748_create_administrators_table.php, sourcecode/apis/contentauthor/database/migrations/2019_11_05_112216_add_ndla_css_timestamp.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
1. Remove creation of useless default user
This creates a predictable password which would essentially function like a backdoor, except CA does not match passwords stored as MD5 hashes. Since the hash is not usable, creating this account has no purpose anyway.
2. Don't invoke application code when inserting H5P option
This invokes `H5POptionObserver` which then tries interacting with the cache, which might not be available at the time of running migrations. Additionally, migrations have to take the DB state up until the point it's ran into consideration, therefore it should not rely on application code which could change at any point.
=> Fix some migrations

sourcecode/apis/contentauthor/resources/assets/react/components/H5pEditor/List/getTextFields.js, sourcecode/apis/contentauthor/tests/Integration/Article/ArticleTest.php
CA Script View fixes:
- Issue where fields are not displayed
- Using `csv-to-text` widget on text-fields will not prevent it from displaying
- Update list of field names used as alt-text for images
=> GH #2722, #2623, #2203: Fields not displaying in script view

docker-compose.yml, sourcecode/apis/contentauthor/Dockerfile
`npm install` alters package.json, which is undesirable.
https://docs.npmjs.com/cli/v10/commands/npm-ci
`--legacy-peer-deps` isn't necessary since 1a8424e0b293701ea8105f5b9fbc2b741a7c9a30, but that commit did not remove it from docker-compose.yml.
=> use `npm ci` for CA

docker-compose.yml, sourcecode/apis/contentauthor/Dockerfile, sourcecode/apis/contentauthor/config/filesystems.php, sourcecode/apis/contentauthor/docker/php/docker-entrypoint-dev.sh
Creates a symlink at `/app/public/h5pstorage` that points to `/app/storage/app`.
The symlink is relative, so should be visible and working in the IDE outside the container, too.
This should have no effect on live environments, since these use S3.
=> fix h5pstorage symlink properly

sourcecode/apis/contentauthor/resources/assets/ckeditor/config.js, sourcecode/apis/contentauthor/resources/assets/ckeditor/inline-config.js
Disable CKEditor version check that displays a popup in the editor saying the editor is unsafe and should be updated. The latest, and last, open source version, 4.22.1,  is already in use. Newer versions are available under commercial terms. The check was added in 4.22.0 and is default enabled.
This disables the check in Article and Question content types, and in H5P Script view. The editor used by H5P is included in the H5P Editor composer package and is currently at version 4.17.1.
=> Disable CKEditor version check

sourcecode/apis/contentauthor/app/Http/Controllers/ArticleController.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/resources/lang/en/h5p-editor.php, sourcecode/apis/contentauthor/resources/lang/ko/h5p-editor.php, sourcecode/apis/contentauthor/resources/lang/nb/h5p-editor.php, sourcecode/apis/contentauthor/resources/lang/nn/h5p-editor.php, sourcecode/apis/contentauthor/resources/lang/sv/h5p-editor.php, sourcecode/apis/contentauthor/resources/views/h5p/index.blade.php, sourcecode/apis/contentauthor/routes/web.php
Discovered while working on #2768 
Removes `GET /h5p` and similar routes created by `Route::resource()` that either do not have a corresponding controller method, or just 404.
=> remove unused index routes

sourcecode/hub/app/View/Components/LtiLaunch.php, sourcecode/hub/resources/js/resize.js, sourcecode/hub/resources/views/components/launch.blade.php, sourcecode/hub/resources/views/content/embed.blade.php
This fixes a bug where e.g. previewing content that emits resize messages would signal to Edlib's parent frame that Edlib must be resized, even as Edlib is currently displaying more than just the content.
The `@props` rubbish is removed, as it interferes with `$attributes`.
Fixes #2804
=> only forward resize messages in embed view

sourcecode/hub/resources/views/components/launch.blade.php
`$attributes` apparently doesn't contain attributes defined by a class-backed component.
=> restore iframe dimensions

sourcecode/hub/Dockerfile, sourcecode/hub/docker/nginx/server_tokens.conf, sourcecode/hub/docker/php/php-dev.ini, sourcecode/hub/docker/php/php.ini
As was done with CA, secures against low-effort "security" reports.
=> hub: do not expose server versions

sourcecode/hub/app/Console/Commands/AddLtiTool.php, sourcecode/hub/app/Http/Requests/StoreLtiToolExtraRequest.php, sourcecode/hub/app/Http/Requests/StoreLtiToolRequest.php, sourcecode/hub/app/Models/LtiTool.php, sourcecode/hub/app/Models/LtiToolExtra.php, sourcecode/hub/database/factories/LtiToolExtraFactory.php, sourcecode/hub/database/factories/LtiToolFactory.php, sourcecode/hub/database/migrations/2024_12_11_080000_add_lti_tool_slug.php, sourcecode/hub/lang/en/messages.php, sourcecode/hub/resources/views/admin/lti-tools/add-extra.blade.php, sourcecode/hub/resources/views/admin/lti-tools/add.blade.php, sourcecode/hub/resources/views/admin/lti-tools/index.blade.php, sourcecode/hub/routes/web.php, sourcecode/hub/tests/Browser/AdminTest.php, sourcecode/hub/tests/Browser/ContentTest.php, sourcecode/hub/tests/DuskTestCase.php, sourcecode/hub/tests/Feature/Admin/AdminTest.php, sourcecode/hub/tests/Feature/Commands/AddLtiToolTest.php
Adds human-friendly URL slugs for LTI tools and the non-admin extras.
Before (awful):
- https://hub.edlib.test/content/create/01j713jgj0yfp0zac2ffb0myjg
- https://hub.edlib.test/content/create/01j713jgj0yfp0zac2ffb0myjg/01jeb378mhgabn5fpwajpt95sn
After:
- https://hub.edlib.test/content/create/contentauthor
- https://hub.edlib.test/content/create/contentauthor/article
The ID is used as the slug for existing tools.
=> hub: add url slugs for tools

sourcecode/hub/app/Http/Requests/UpdateLtiToolRequest.php, sourcecode/hub/database/factories/LtiToolFactory.php, sourcecode/hub/resources/views/admin/lti-tools/index.blade.php, sourcecode/hub/tests/Browser/AdminTest.php, sourcecode/hub/tests/Browser/Components/LtiToolCard.php
`$tool->fill($request->validated())` didn't work correctly, as unchecked checkboxes don't "exist" in the form data.
=> hub: fix unsetting flags on tools

sourcecode/apis/contentauthor/app/Http/Controllers/API/LockStatusController.php, sourcecode/apis/contentauthor/tests/Integration/Content/LockStatusTest.php, sourcecode/apis/contentauthor/tests/Integration/Models/ContentLockTest.php
The race condition:
The `updated_at` was updated by doing a POST to the `lock.status` endpoint. Then the `ContentLock` model was used to update the `created_at` value, `updated_at` would be set by the framework and could get a new value. The  test assumed that `updated_at` would be unchanged by the model update.
- Move testing of lock update from `testLockStatusWithActivePulseButExpired()` to new test `testLockUpdate()`
- Add tests for `ContentLock` model functions
- Minor adjustment in `LockStatusController::pulse()` to make it more readable
=> GH #2855: Fix race condition in LockStatusTest

sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/assets/js/admin.js, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php
Content type and libraries could be deleted if content did not use it as main content type, or if was not referenced by other content types or libraries.
Content types can use other content types dynamically, e.g. Course Presentation, this use is not stored in `h5p_libraries_libraries`. This adds a check if see if any content references the library by using `h5p_contents_libraries`.
=> CA Admin: Prevent deleting library if used by content or other libraries

sourcecode/hub/composer.json, sourcecode/hub/composer.lock, sourcecode/hub/phpstan.dist.neon
Similar to what CA has. Primarily to avoid committing `dd()` and such.
=> make phpstan warn about misused functions/statements

sourcecode/apis/contentauthor/app/Http/Controllers/API/LockStatusController.php, sourcecode/apis/contentauthor/app/Http/Controllers/ArticleController.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Http/Controllers/QuestionSetController.php, sourcecode/apis/contentauthor/app/Libraries/Games/Millionaire/Millionaire.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PConfigAbstract.php, sourcecode/apis/contentauthor/config/app.php, sourcecode/apis/contentauthor/config/ndla-mode.php, sourcecode/apis/contentauthor/config/ndlaprod/h5p.php
This is used to override a single environment variable that could just be set correctly to begin with.
Even Edlib 2 [marked this as to be removed](https://github.com/cerpus/Edlib/blame/edlib2/chart/templates/common.yaml#L49-L50).
=> remove use of profile "helper"

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/assets/js/admin.js, sourcecode/apis/contentauthor/resources/assets/sass/admin.scss, sourcecode/apis/contentauthor/resources/assets/sass/navtabs.scss, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/fragments/update-explanation.blade.php, sourcecode/apis/contentauthor/resources/views/admin/index.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/update-content-type-cache.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/upload-content-type.blade.php, sourcecode/apis/contentauthor/resources/views/layouts/admin.blade.php
The "Update libraries" page can be quite long, containing both upload and listing of content types and libraries. This splits the long page into four parts using tabs; 'Installed content types', 'Installed libraries', 'Upload content type' and 'Install from h5p.org'. Info/help text was also added on each tab.
Menu item 'Update libraries' is rename to 'Manage content types'.
=> CA Admin: Use tabs on manage content type page, add descriptions and help text. Rename 'Update libraries' to 'Manage content types'

sourcecode/hub/app/Http/Controllers/ContentController.php, sourcecode/hub/app/Models/ContentVersion.php, sourcecode/hub/composer.lock
When user selects or edit content, the response can contain info about owner
=> Add owner info to use/edit response

sourcecode/apis/contentauthor/.php-cs-fixer.dist.php
When run from command line `php-cs-fixer` fails when trying to access a folder in `storage/app` that it doesn't have access to.
This adjusts the paths that `php-cs-fixer` checks.
The original config used `path()` to add folders, this function includes files/folders that contains the provided string in the path.
So `->path('app')` would include all files in the `app` folder but also any other file/folder containing the string `app`, e.g. `/storage/app/` and the file `public/js/h5p/ckeditor_wiris/integration/lib/com/wiris/system/CallWrapper.class.php` (the filename contains 'app')
=> CA: Adjust paths for php-cs-fixer

sourcecode/hub/app/Http/Controllers/ContentController.php, sourcecode/hub/app/Http/Controllers/NdlaLegacy/OembedController.php
1. Show the requested version, not the latest published one, when embedding
2. Return facade URLs for NDLA.
=> Fix minor issues with versions and inserted URLs

sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/database/migrations/2025_02_07_124500_create_h5p_contents_libraries_library_id_index.php
Add missing database index on `h5p_contents_libraries.library_id`
Usage data for content type/library was already retrieved, so reuse that
=> GH #2944: CA Admin: Fix slow check if content type/library can be deleted

sourcecode/hub/.env.example, sourcecode/hub/app/Http/Controllers/ContentController.php, sourcecode/hub/app/Providers/RouteServiceProvider.php, sourcecode/hub/config/app.php, sourcecode/hub/phpunit.xml, sourcecode/hub/routes/edlib-legacy.php, sourcecode/hub/tests/Feature/ContentTest.php
Redirects `/s/resources/<uuid>` on a configurable domain to the hub's embed equivalent for that content.
=> add redirect for legacy e2 urls

docs/docs/hosting/ca-setup.mdx
=> fix documentation mistake

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminH5PDetailsController.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/content-details.blade.php, sourcecode/apis/contentauthor/routes/admin.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/Admin/AdminH5PDetailsControllerTest.php
Listing of content versions did not list all versions. Not all changes in CA causes a new content id, but a new version is always created, so one content id can have multiple versions. Since the data was collected using content id as key, not all versions was included, this also caused some child content to not be included causing an exception when displaying the page.
Data is now collected using the version id as key.
=> CA Admin: Fix listing of content versions

sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/content-details.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-content.blade.php
Remove Edlib 2 info, Folium Id and listed, remove unnecessary specification on created and updated dates, it's all CA now.
=> CA Admin: Remove Edlib 2 info

docs/docs/hosting/ca-setup.mdx, sourcecode/hub/app/Console/Commands/AddLtiTool.php, sourcecode/hub/app/Http/Requests/StoreLtiToolRequest.php, sourcecode/hub/app/Http/Requests/UpdateLtiToolRequest.php, sourcecode/hub/app/Models/ContentVersion.php, sourcecode/hub/app/Models/LtiTool.php, sourcecode/hub/app/Transformers/LtiToolTransformer.php, sourcecode/hub/database/factories/LtiToolFactory.php, sourcecode/hub/database/migrations/2025_02_10_remove_lti_tools_proxy_launch.php, sourcecode/hub/lang/en/messages.php, sourcecode/hub/lang/nb/messages.php, sourcecode/hub/resources/views/admin/lti-tools/index.blade.php, sourcecode/hub/resources/views/components/admin/lti-tools/form.blade.php, sourcecode/hub/tests/Browser/AdminTest.php, sourcecode/hub/tests/Browser/Components/LtiToolCard.php, sourcecode/hub/tests/Feature/Api/LtiToolTest.php, sourcecode/hub/tests/Feature/Commands/AddLtiToolTest.php, sourcecode/hub/tests/Feature/ContentVersionTest.php
Removes the 'proxy launch' setting. With this disabled, Edlib would return a direct URL to the tool (e.g. Content Author) upon insertion, instead of a URL to the Hub, which would only work if the platform and the tool had exchanged keys in advance.
Adding this setting on the tool level was a mistake, but returning direct URLs might be useful in some circumstances. It could be brought back as an instance or LTI platform setting later, but right now there isn't much use for it.
=> remove lti_tools.proxy_launch

docker-compose.yml, sourcecode/hub/routes/edlib-legacy.php, sourcecode/hub/tests/Feature/EdlibLegacyTest.php
Additionally, `www.edlib.com` is removed from docker-compose.yml since it's not actually used by a browser test.
=> add www redirect for ndla

sourcecode/hub/resources/views/components/launch.blade.php, sourcecode/hub/resources/views/ndla-legacy/oembed.blade.php
Set same permissions as used on h5p.org
Also setting `allowfullscreen` as the `allow.fullscreen` is not supported on all browsers e.g. Safari
=> GH #3031: Set iframe permissions

sourcecode/apis/contentauthor/app/Http/Controllers/NdlaContentController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Audio/NdlaAudioAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PCreateConfig.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PEditConfig.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Image/NdlaImageAdapter.php, sourcecode/apis/contentauthor/config/ndla.php, sourcecode/apis/contentauthor/resources/assets/js/ndla.js, sourcecode/apis/contentauthor/resources/assets/react/components/AudioBrowser/AudioBrowserContainer.js, sourcecode/apis/contentauthor/resources/assets/react/components/ImageBrowser/ImageBrowserContainer.js, sourcecode/apis/contentauthor/resources/assets/react/contentBrowser.js, sourcecode/apis/contentauthor/routes/web.php
- Set search parameters for NDLA Image API query:
- fallback => NDLA_H5P_IMAGE_SEARCH_FALLBACK, default `true`
- license => NDLA_H5P_IMAGE_SEARCH_LICENSE, default `'all'`
- page-size => NDLA_H5P_IMAGE_SEARCH_PAGESIZE. default `15`
- Set search parameters for NDLA Audio API query:
- fallback => NDLA_H5P_AUDIO_SEARCH_FALLBACK, default `true`
- license => NDLA_H5P_AUDIO_SEARCH_LICENSE, default `'all'`
- page-size => NDLA_H5P_AUDIO_SEARCH_PAGESIZE. default `10`
- Client uses API directly for search instead of through CA
=> GH #3038: Set searchparams for NDLA Audio and Image API

sourcecode/apis/contentauthor/app/Libraries/H5P/H5PConfigAbstract.php, sourcecode/apis/contentauthor/public/js/editor-setup.js
In CA Editor it is possible to update content to a newer version of the H5P content type used.
A script required for the update to function was not loaded after PR #3008. The script also modified CKEditor settings, this is removed from the script and the script will now be loaded again.
=> GH #3051: Fix fail to upgrade content to newer H5P content type version in Editor

docs/docs/developers/content-types.mdx, sourcecode/hub/app/Events/LaunchItemSelection.php, sourcecode/hub/app/Http/Requests/StoreLtiToolRequest.php, sourcecode/hub/app/Http/Requests/UpdateLtiToolRequest.php, sourcecode/hub/app/Listeners/AddContentStatusFlagsToLtiLaunch.php, sourcecode/hub/app/Lti/LtiLaunchBuilder.php, sourcecode/hub/app/Models/LtiTool.php, sourcecode/hub/app/Transformers/LtiToolTransformer.php, sourcecode/hub/database/factories/LtiToolFactory.php, sourcecode/hub/database/migrations/2025_03_19_add_default_tool_flags.php, sourcecode/hub/lang/en/messages.php, sourcecode/hub/resources/views/admin/lti-tools/index.blade.php, sourcecode/hub/resources/views/components/admin/lti-tools/form.blade.php, sourcecode/hub/tests/Feature/Api/LtiToolTest.php, sourcecode/hub/tests/Feature/LtiPlatformTest.php
Add new tool settings for deciding the default values of the published/shared flags when creating content.
=> hub: send default published/shared flags
