cerpus/Edlib

docker-compose.yml
Temporary fix for build issues with docker-compose.
=> mount all node_modules directories on named volumes

sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/QuestionContentType.js, sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/QuestionContentTypeLayout.js, sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AnswerList/AnswerListLayout.js, sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionContainer/index.js
Add pops missing in validation, remove unused import, minor code cleanup
=> Resolves #24: Show correct/wrong toggle for first answer option

sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/CerpusH5PAdapter.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php
=> use Common HTML renderer for MathJax

.github/workflows/dependabot-auto-approve.yaml, .github/workflows/dependabot-auto-merge.yaml
Auto merging means all test must pass in order to be merged
=> Add auto merging of minor versions

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminController.php
=> Fix bad use of str_contains

sourcecode/apis/contentauthor/app/Http/Libraries/ContentTypes/ContentTypeInterface.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Importers/ArticleImporter.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Importers/ImporterBase.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Importers/PackageImporter.php, sourcecode/apis/contentauthor/app/Messaging/queues.php, sourcecode/apis/contentauthor/phpunit.xml, sourcecode/apis/contentauthor/tests/Middleware/Oauth10VerificationTest.php, sourcecode/apis/contentauthor/tests/bootstrap.php
- phpunit.xml settings not taking effect
- fail to run unit-tests with code coverage
=> Unittest fixes

sourcecode/apis/contentauthor/public/js/videos/brightcove.js
=> Support brightcove 360 videos

sourcecode/apis/auth/src/controllers/token.js
=> Verify if externaltoken is in request and throw 422 if not

sourcecode/apis/auth/package.json, sourcecode/apis/auth/yarn.lock, sourcecode/apis/doku/package.json, sourcecode/apis/doku/yarn.lock, sourcecode/apis/lti/package.json, sourcecode/apis/lti/yarn.lock, sourcecode/apis/resources/package.json, sourcecode/apis/resources/yarn.lock, sourcecode/apis/url/package.json, sourcecode/apis/url/yarn.lock, sourcecode/npm/nodeUtils/package.json, sourcecode/npm/nodeUtils/src/apiClients/auth/index.js, sourcecode/npm/nodeUtils/src/apiClients/edlibAuth/index.js, sourcecode/npm/nodeUtils/src/middlewares/addUserToRequest.js, sourcecode/npm/nodeUtils/src/services/__tests__/auth.js, sourcecode/npm/nodeUtils/src/services/auth.js, sourcecode/npm/nodeUtils/yarn.lock, sourcecode/proxies/auth/package.json, sourcecode/proxies/auth/yarn.lock, sourcecode/proxies/doku/package.json, sourcecode/proxies/doku/yarn.lock, sourcecode/proxies/lti/package.json, sourcecode/proxies/lti/yarn.lock, sourcecode/proxies/resource/package.json, sourcecode/proxies/resource/yarn.lock, sourcecode/proxies/url/package.json, sourcecode/proxies/url/yarn.lock
=> Improve auth error handling and add test

.github/workflows/docs-edlib-com.yaml, sourcecode/docs/docs.edlib.com/Dockerfile
=> Add new check for docs to detect broken links

sourcecode/docs/docs.edlib.com/blog/19-01-2022-gardening-the-plant.md
#2 blog post.
About the work we've done the last months.
=> New blog post

sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php
Fixes an issue where `POST /lti-content/{id}` with a valid ID would result in a 404 if the content exists, but an exception happens (e.g. a file is not found). Non-existent content will still result in a 404 after this change.
=> Don't eat exceptions in H5PController::doShow

sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php
=> remove non ascii from filename to avoid error

sourcecode/apis/contentauthor/app/Auth/Guards/EdlibGuard.php, sourcecode/apis/contentauthor/app/Http/Middleware/EdlibParseJwt.php, sourcecode/apis/contentauthor/app/Providers/AuthServiceProvider.php, sourcecode/apis/contentauthor/config/auth.php
Authentication does not work on test anymore. This fixes that
=> Fix login issues

sourcecode/apis/contentauthor/app/Providers/AppServiceProvider.php
Remove the unused `Collection::recursive` macro.
=> Remove unused macro

sourcecode/docs/docs.edlib.com/docs/product/roadmap.mdx
=> Updated roadmap note

sourcecode/docs/docs.edlib.com/src/pages/contact-us.md
=> Updated contact info on contact-us

sourcecode/docs/docs.edlib.com/docs/developers/translation.mdx
Changed documentation towards Weblate-translation.
=> Updated translation documentation (adjustments)

AUTHORS.md
Added new names and changes some roles.
=> Updated creators and maintainers

sourcecode/apis/contentauthor/app/H5PLibrary.php
=> Don't include image width for H5P.NDLAThreeImage

sourcecode/apis/resources/src/context/index.js, sourcecode/apis/resources/src/migrations/20201102113940_resourceSearch.cjs, sourcecode/apis/resources/src/migrations/20201102113941_resourceSearchFilters.cjs, sourcecode/apis/resources/src/repositories/resourceSearch.js, sourcecode/apis/resources/src/repositories/resourceSearchFilter.js, sourcecode/apis/resources/src/services/resource.js
=> Add logging of searches

sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock
Old version has a version constraint that blocks installation of php-amqplib >= 3.1.
=> use cerpus/laravel-rabbitmq-pubsub:^2

sourcecode/www/src/routes/routes/StandaloneComponents/components/ContentExplorer/routes/EditResource.jsx
=> Fix blank screen for NDLA

CODE_OF_CONDUCT.md
Updated email address to edlib-support.
=> Updated email

sourcecode/docs/docs.edlib.com/blog/19-01-2022-gardening-the-plant.md
=> Fixed nasty English

sourcecode/docs/docs.edlib.com/docs/community/contributing.mdx
Add section about translating Edlib
=> Add section about translating Edlib

sourcecode/docs/docs.edlib.com/blog/19-01-2022-gardening-the-plant.md
Translating Edlib and release overview were mixed up.
=> Fixed mix-up with URLs

sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/config/edlib-resource-kit.php, sourcecode/apis/contentauthor/tests/Traits/MockMQ.php
Adds support for synchronous resource publishing via `edlib-resource-kit.synchronous-resource-manager` flag.
=> upgrade cerpus/edlib-resource-kit-laravel

sourcecode/apis/contentauthor/app/Http/Controllers/API/Transformers/AnswerTransformer.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/Transformers/QuestionTransformer.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/Transformers/QuestionsetTransformer.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Exporters/Transformers/CourseTransformer.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Exporters/Transformers/ModuleTransformer.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Exporters/Transformers/ResourceTransformer.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Exporters/Transformers/SubjectTransformer.php, sourcecode/apis/contentauthor/app/Libraries/NDLA/Exporters/Transformers/SubtopicModuleTransformer.php, sourcecode/apis/contentauthor/app/Transformers/DateTransformer.php, sourcecode/apis/contentauthor/app/Transformers/LinkMetadataTransformer.php, sourcecode/apis/contentauthor/app/Transformers/QuestionSetsQuestionAnswerTransformer.php, sourcecode/apis/contentauthor/app/Transformers/QuestionSetsQuestionTransformer.php, sourcecode/apis/contentauthor/app/Transformers/QuestionSetsTransformer.php, sourcecode/apis/contentauthor/app/Transformers/Serializers/ArraySerializer.php
Somehow dependabot updated league/fractal to a version with breaking changes, in spite of tests failing. Update the code to be compatible.
=> Fix Fractal transformers/serializers

CODE_OF_CONDUCT.md
Minor changes to language to improve flow and correctness.
Changed mailto link description to correspond to the actual mail address.
Changed version to v.1.0.1.
=> Code of Conduct language change

sourcecode/apis/contentauthor/app/CollaboratorContext.php, sourcecode/apis/contentauthor/app/Exceptions/H5pImportException.php, sourcecode/apis/contentauthor/app/File.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/H5PImportController.php, sourcecode/apis/contentauthor/app/Http/Controllers/API/QuestionsetController.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/ContentUpgradeController.php, sourcecode/apis/contentauthor/app/Http/Controllers/ArticleController.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Http/Controllers/QuestionSetController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php, sourcecode/apis/contentauthor/app/Libraries/H5P/H5PImport.php, sourcecode/apis/contentauthor/app/Libraries/QuestionSet/QuestionSetHandler.php, sourcecode/apis/contentauthor/app/Listeners/AbstractHandleVersioning.php, sourcecode/apis/contentauthor/app/Listeners/Article/HandleCollaborationInviteEmails.php, sourcecode/apis/contentauthor/app/Listeners/Questionset/HandleQuestionbank.php, sourcecode/apis/contentauthor/app/Observers/H5POptionObserver.php, sourcecode/apis/contentauthor/tests/Feature/QuestionSetAPITest.php
=> Let exceptions bubble up

sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/config/ndla-mode.php, sourcecode/apis/contentauthor/config/ndlaprod/feature.php
Publish toggle should now be enabled in the NDLA environment
=> GH #989: Remove NDLA config that controls Publish-toggle

sourcecode/www/src/components/ResourcePage/ResourcePage.jsx
I've deliberately avoided updating the breakpoints in the themes, since I don't think they will be useful defaults.
=> Increase the breakpoint between card & table view

sourcecode/docs/docs.edlib.com/docs/product/caseStudies/gamilab.mdx
Good enough version for the air.
=> Gamilab case study update

sourcecode/docs/docs.edlib.com/docs/product/features.mdx
- Removed some outdated features from "Existing Features"
- Added missing text to paragraphs: versioning and language support
=> Update to missing paragraphs

sourcecode/docs/docs.edlib.com/docs/product/caseStudies/gamilab.mdx
A couple of minor updates after feedback from Runar.
=> Minor updates.

sourcecode/apis/contentauthor/.gitignore, sourcecode/apis/contentauthor/public/js/presave/H5P.Crossword/presave.js, sourcecode/apis/contentauthor/public/js/presave/H5P.MultiMediaChoice/presave.js, sourcecode/apis/contentauthor/public/js/presave/H5P.SortParagraphs/presave.js
- H5P.Crossword
- H5P.MultiMediaChoice
- H5P.SortParagraphs
=> GH #1264: Add max score handling to new h5p types

sourcecode/docs/docs.edlib.com/docs/support/userGuides/create-content.mdx
Removed info about "text" content type that is no longer available for creating new content.
=> Removed "text"

sourcecode/docs/docs.edlib.com/docs/product/caseStudies/gamilab.mdx
Updated case study with removal of  references to the article content type "text"
=> Updated case study without mention of "text"

sourcecode/docs/docs.edlib.com/docs/product/roadmap.mdx
=> Updated roadmap Q3

sourcecode/apis/contentauthor/app/Article.php, sourcecode/apis/contentauthor/app/Content.php, sourcecode/apis/contentauthor/app/ContentLanguage.php, sourcecode/apis/contentauthor/app/ContentLock.php, sourcecode/apis/contentauthor/app/Game.php, sourcecode/apis/contentauthor/app/Gametype.php, sourcecode/apis/contentauthor/app/H5PCollaborator.php, sourcecode/apis/contentauthor/app/H5PContent.php, sourcecode/apis/contentauthor/app/H5PLibrariesHubCache.php, sourcecode/apis/contentauthor/app/Link.php, sourcecode/apis/contentauthor/app/NdlaIdMapper.php, sourcecode/apis/contentauthor/app/QuestionSet.php, sourcecode/apis/contentauthor/app/QuestionSetQuestion.php, sourcecode/apis/contentauthor/app/QuestionSetQuestionAnswer.php, sourcecode/apis/contentauthor/app/Traits/Collaboratable.php, sourcecode/apis/contentauthor/app/Traits/HasLanguage.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
PHPstan complains about the non-standard syntax.
See https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/property.html#property-property-read-property-write
=> Use the correct, documented formatting of property PHPDoc annotations

sourcecode/docs/docs.edlib.com/docs/product/roadmap.mdx
Referenced user to the discussion section on GitHub and contact us directly.
=> Updated with small fix

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/index.blade.php
- New columns: machinename, summary
- Split existing and new to separate lists
- New button for new libraries list: external link
- Sort by machine name
=> GH #1500: Admin library list improvements

sourcecode/docs/docs.edlib.com/docs/developers/api-documentation/introduction.mdx
Some info about the work we are doing and why documentation is missing.
=> Updated intro

sourcecode/docs/docs.edlib.com/docs/support/faq.mdx
Updated faq with link to developers section for build and deploy
=> Updated faq with link to developers section

sourcecode/docs/docs.edlib.com/docs/product/ecosystem.mdx
Updated info about the H5P-ecosystem and how we and others use it.
=> Updated info about the H5P-ecosystem

sourcecode/docs/docs.edlib.com/docusaurus.config.js
Navbar title commented out.
Added navbar hide on scroll function
Closes #1524
=> Removed title from navbar

sourcecode/apis/resources/src/services/resource.js
@chrieinv Could you try this and see if it returns expected results?
=> Load view count from database instead of ES

sourcecode/docs/docs.edlib.com/src/pages/contact-us.md
The best way of getting in touch with the Edlib team is through email or GitHub.
=> Removed phone number

sourcecode/apis/contentauthor/app/H5PContent.php, sourcecode/apis/contentauthor/app/H5PLibrary.php, sourcecode/apis/contentauthor/app/Http/Controllers/H5PController.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Framework.php
=> Fix broken library lookup

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/views/admin/fragments/dependency-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-check.blade.php
- Display semantics content instead of just length
- Minor improvements
=> GH #1681: Fix failing to read files

sourcecode/docs/docs.edlib.com/docs/product/caseStudies/ndla.mdx
Fixed section about Joubel adding the new name.
=> Update name on Joubel

sourcecode/docs/docs.edlib.com/docs/developers/config-variables/_category_.json, sourcecode/docs/docs.edlib.com/docs/developers/config-variables/h5p-config.mdx, sourcecode/docs/docs.edlib.com/docs/developers/language.mdx, sourcecode/docs/docs.edlib.com/docs/developers/thirdPartyContent/h5p/max-score/writing.mdx, sourcecode/docs/docs.edlib.com/docusaurus.config.js
- Add page for H5P config settings
- Add page about language
- Fix incorrect path in maxScore docs
=> Documentation update

sourcecode/apis/resources/src/controllers/stats.js, sourcecode/www/src/components/ResourceModal/ResourceStats.jsx, sourcecode/www/src/i18n/en/translation.json, sourcecode/www/src/i18n/nb/translation.json
=> make views stats on preview display more by default

chart/templates/apis/contentauthor.yaml
=> #1821 - Enable download button for H5P

sourcecode/apis/contentauthor/app/ApiModels/Resource.php, sourcecode/apis/contentauthor/app/Apis/ResourceApiService.php, sourcecode/apis/contentauthor/app/Libraries/H5P/ViewConfig.php
=> #752-Update H5P embed settings

sourcecode/www/src/components/LanguageDropdown.jsx, sourcecode/www/src/components/ResourceFilters/Filters/H5PTypes/Alphabetical.jsx, sourcecode/www/src/components/ResourceFilters/Filters/H5PTypes/Grouped.jsx, sourcecode/www/src/components/ResourceFilters/Filters/Licenses.jsx, sourcecode/www/src/components/ResourcePage/ResourcePage.jsx
Sort languages alphabetically
Disable filters that gives zero content
=> GH #1825: Display number of content in the language select

sourcecode/apis/contentauthor/.gitignore, sourcecode/apis/contentauthor/app/Libraries/H5P/Adapters/NDLAH5PAdapter.php, sourcecode/apis/contentauthor/public/css/ndlah5p-youtube.css, sourcecode/apis/contentauthor/public/js/h5p/ndla-contentbrowser.js, sourcecode/apis/contentauthor/public/js/h5p/ndlah5p-youtube.js
=> #618 Disable YouTube in H5P for NDLA

.gitignore
* Ignore `*.iml` (IntelliJ IDEA files)
* Ignore **all** `*.phar` files, these should never be committed
* Ignore Docker Compose overrides
* Simplify other rules
=> Fix .gitignore annoyances

sourcecode/apis/common/composer.json, sourcecode/apis/common/composer.lock
See https://github.com/packbackbooks/lti-1-3-php-library/issues/77
=> fix LTI 1.3 launch failure

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/GamesAdminController.php, sourcecode/apis/contentauthor/app/Http/Requests/GameUploadRequest.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
=> fix game uploads

AUTHORS.md
Added Stalin and Kashif as creators/maintainers.
=> Added authors

sourcecode/apis/contentauthor/app/Libraries/H5P/TranslationServices/NynorobotAdapter.php, sourcecode/apis/contentauthor/app/Providers/H5PServiceProvider.php, sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/config/h5p.php, sourcecode/apis/contentauthor/config/services.php, sourcecode/apis/contentauthor/tests/Unit/Libraries/H5P/TranslationServices/NynorobotAdapterTest.php
Not yet tested against the real service.
=> add Nynorobot translator adapter

sourcecode/apis/contentauthor/app/Console/Commands/VersionAllUnversionedContent.php, sourcecode/apis/contentauthor/app/Http/Middleware/LtiRequestAuth.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
Bugs pointed out by phpstan and fixed:
* `Session::put()` does not take a third argument.
* H5PContent does not have an `owner_id` property
=> fix phpstan failure, minor bugs

.github/workflows/weblate-auto-approve.yaml
Appropriated dependabot-auto-merge.yaml to create this.
Should auto-merge any PRs from Cerpusbot.
=> Created auto-merge action

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/resources/assets/sass/admin.scss, sourcecode/apis/contentauthor/resources/views/admin/fragments/library-table.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-content.blade.php
Fix minor layout issue on action buttons in library list
=> GH #2179: CA Admin: List only latest version of content on a library as default

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminH5PDetailsController.php, sourcecode/apis/contentauthor/app/Http/Controllers/Admin/LibraryUpgradeController.php, sourcecode/apis/contentauthor/phpstan-baseline.neon, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/content-details.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-check.blade.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/library-content.blade.php, sourcecode/apis/contentauthor/routes/admin.php, sourcecode/apis/contentauthor/tests/Unit/Http/Controllers/AdminH5PDetailsControllerTest.php
Move display of f4m to details view
=> CA admin: Show content details and history

sourcecode/apis/contentauthor/app/Http/Controllers/Admin/AdminH5PDetailsController.php, sourcecode/apis/contentauthor/resources/views/admin/library-upgrade/content-details.blade.php
Don't retrieve child history that is not displayed
=> CA admin: Content history: Handle errors getting f4m and history

sourcecode/proxies/admin/src/components/GenerateCSVWithResourceUrls.jsx, sourcecode/proxies/admin/src/containers/DefaultHookQuery.jsx
This reverts commit 965cb9e1e6f0c338e6777891d9d822314b1fc1c7.
=> Revert "#2189-Something happened error (#2195)"

sourcecode/apis/contentauthor/public/js/h5p/ndla-contentbrowser.js
=> remove mangling of text track URLs

sourcecode/apis/contentauthor/app/User.php, sourcecode/apis/contentauthor/database/factories/ArticleCollaboratorFactory.php, sourcecode/apis/contentauthor/database/factories/ArticleFactory.php, sourcecode/apis/contentauthor/database/factories/CollaboratorContextFactory.php, sourcecode/apis/contentauthor/database/factories/CollaboratorFactory.php, sourcecode/apis/contentauthor/database/factories/ContentLockFactory.php, sourcecode/apis/contentauthor/database/factories/FileFactory.php, sourcecode/apis/contentauthor/database/factories/GameFactory.php, sourcecode/apis/contentauthor/database/factories/GametypeFactory.php, sourcecode/apis/contentauthor/database/factories/H5PCollaboratorFactory.php, sourcecode/apis/contentauthor/database/factories/H5PContentFactory.php, sourcecode/apis/contentauthor/database/factories/H5PContentLibraryFactory.php, sourcecode/apis/contentauthor/database/factories/H5PContentsMetadataFactory.php, sourcecode/apis/contentauthor/database/factories/H5PContentsUserDataFactory.php, sourcecode/apis/contentauthor/database/factories/H5PContentsVideoFactory.php, sourcecode/apis/contentauthor/database/factories/H5PLibraryFactory.php, sourcecode/apis/contentauthor/database/factories/H5PResultFactory.php, sourcecode/apis/contentauthor/database/factories/LinkFactory.php, sourcecode/apis/contentauthor/database/factories/QuestionSetFactory.php, sourcecode/apis/contentauthor/database/factories/QuestionSetQuestionAnswerFactory.php, sourcecode/apis/contentauthor/database/factories/QuestionSetQuestionFactory.php, sourcecode/apis/contentauthor/phpstan-baseline.neon
This solves a substantial amount of problems found by PHPStan.
=> add generic type to database factories

.github/workflows/api-contentauthor.yaml
=> fix invalid workflow usage in CI

sourcecode/docs/docs.edlib.com/docs/developers/getting-started.mdx
Improving the steps in the guide for getting started.
=> Updated getting-started.mdx

docker-compose.yml, sourcecode/apis/contentauthor/.env.example, sourcecode/apis/contentauthor/README.md, sourcecode/apis/contentauthor/app/File.php, sourcecode/apis/contentauthor/app/Gametype.php, sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php, sourcecode/apis/contentauthor/app/Libraries/ContentAuthorStorage.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Interfaces/CerpusStorageInterface.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Storage/H5PCerpusStorage.php, sourcecode/apis/contentauthor/app/Providers/AppServiceProvider.php, sourcecode/apis/contentauthor/config/app.php, sourcecode/apis/contentauthor/config/filesystems.php, sourcecode/apis/contentauthor/docker/contentAuthor.conf.template, sourcecode/apis/contentauthor/routes/web.php, sourcecode/apis/contentauthor/tests/Integration/Article/ArticleTest.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/ContentAssetControllerTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/H5PCopyrightTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/Storage/H5pCerpusStorageTest.php
Reverts #2333 which broke due to changes in master.
=> Revert serving assets from cdn

sourcecode/docs/docs.edlib.com/docusaurus.config.js, sourcecode/docs/docs.edlib.com/package.json, sourcecode/docs/docs.edlib.com/yarn.lock
Update to release version of Docusaurus
Remove unused packages `@mdx-js/react` and `@svgr/webpack`
=> Update to Docusaurus 2.4.1, remove unused packages

sourcecode/apis/contentauthor/app/Libraries/H5P/Interfaces/H5PDownloadInterface.php, sourcecode/apis/contentauthor/app/Libraries/H5P/Storage/H5PCerpusStorage.php
Should avoid OOM issues with exported H5Ps
=> redirect to download of exported h5p

sourcecode/apis/resources/package.json, sourcecode/apis/resources/yarn.lock
Update npm packages, add several missing peer dependencies
=> Update Resource API npm packages, add several missing peer dependencies

sourcecode/proxies/resource/jest.config.json, sourcecode/proxies/resource/package.json, sourcecode/proxies/resource/yarn.lock
- Update npm packages
- Major updates for `jest` and `nodemon`
=> Update proxy resource npm pacakges, add missing peer dependencies

sourcecode/hub/Dockerfile, sourcecode/hub/app/Configuration/Themes.php, sourcecode/hub/app/Http/Controllers/UserController.php, sourcecode/hub/app/Http/Requests/SavePreferencesRequest.php, sourcecode/hub/app/Models/User.php, sourcecode/hub/database/migrations/2023_08_31_080000_add_user_theme_setting.php, sourcecode/hub/lang/en/messages.php, sourcecode/hub/lang/nb/messages.php, sourcecode/hub/package-lock.json, sourcecode/hub/package.json, sourcecode/hub/resources/views/components/layout/base.blade.php, sourcecode/hub/resources/views/user/preferences.blade.php, sourcecode/hub/tests/Browser/UserTest.php
Be able to select your theme in the user preferences.
This is helpful for development, as it can reveal problems about the colours variables in use.
=> Add preference for theme

sourcecode/apis/contentauthor/app/Http/Controllers/Auth/LoginController.php, sourcecode/apis/contentauthor/routes/admin.php
Unsupported since JWT support was ripped out.
=> Remove remnants of unsupported SSO login in CA

sourcecode/apis/contentauthor/tests/Integration/Article/ArticleTest.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/ArticleControllerTest.php, sourcecode/apis/contentauthor/tests/Integration/Http/Controllers/QuestionSetControllerTest.php, sourcecode/apis/contentauthor/tests/Integration/Libraries/H5P/CRUTest.php
Does not fix the errors logged by `tests/Integration/Http/Controllers/LinkControllerTest.php` as the test(s) causing the error to be logged will be removed by PR #2616
=> Fix errors logged by tests

sourcecode/apis/contentauthor/production.Dockerfile, sourcecode/apis/contentauthor/staging.Dockerfile, sourcecode/apis/contentauthor/vapor.yml, sourcecode/hub/vapor.yml
Changes:
- New DB for hub to fix migrate error
- Re-add assets after initial deploy to Vapor
- Add Dockerfiles to CA for Vapor deploy
=> Fix deploy for CA and Hub

AUTHORS.md, README.md
Update authors and URL on Readme.
=> Author and URL

AUTHORS.md, docs/docs/product/roadmap.mdx
Updated with Q1 roadmap and new author
=> Roadmap and authors

README.md, docs/docs/product/roadmap.mdx, docs/src/components/HomepageFeatures.js
- Roadmap Q2
- Clanup on readme
- Minor edit on docs frontpage
=> Roadmap Q2 and updates

sourcecode/apis/contentauthor/app/Libraries/H5P/TranslationServices/NynorobotAdapter.php, sourcecode/apis/contentauthor/config/services.php
Change style template to NDLA custom, not added as config since only supported endpoint is also NDLA custom
=> GH #2715: Change style template for Nynorobot

sourcecode/apis/contentauthor/app/Console/Commands/H5PLibraryInstall.php
For automation, it is crucial to know if the command succeeded or not.
=> exit with error on failed library install

sourcecode/apis/contentauthor/routes/web.php
=> CA: fix /lti-content/create/h5p

sourcecode/apis/contentauthor/composer.json, sourcecode/apis/contentauthor/composer.lock, sourcecode/apis/contentauthor/config/app.php, sourcecode/apis/contentauthor/resources/views/admin/libraries.blade.php, sourcecode/apis/contentauthor/resources/views/h5p/create.blade.php, sourcecode/apis/contentauthor/resources/views/h5p/edit.blade.php, sourcecode/apis/contentauthor/resources/views/h5p/show.blade.php, sourcecode/apis/contentauthor/resources/views/link/create.blade.php, sourcecode/apis/contentauthor/resources/views/link/edit.blade.php
This just complicates the dependency tree and adds technical debt to avoid writing a tiny bit of HTML. Not worth it.
=> CA: remove dependency on laravelcollective/html

sourcecode/hub/lang/en/messages.php, sourcecode/hub/lang/nb/messages.php, sourcecode/hub/resources/views/content/create.blade.php
=> use translation on /content/create, add admin shortcut

docs/src/css/custom.css
Less noisy default green and a lighter dark mode green to complement it.
=> Update css with better greens

sourcecode/hub/resources/views/components/self-submitting-form.blade.php
=> Fix query params in self-submitting form with GET method

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/docs/developers/contributing/contributing.mdx, docs/src/pages/contact-us.md
Update texts where Cerpus is mentioned.
=> Minor textual updates

sourcecode/hub/resources/css/app.scss, sourcecode/hub/resources/css/layout.scss, sourcecode/hub/resources/css/theme-dark.scss, sourcecode/hub/resources/css/theme-edlib.scss
Fix low contrast on secondary outline button in dark mode
=> Move dark theme to own file, rename edlib theme file. 

docs/docusaurus.config.js, docs/src/pages/contact-us.md, docs/src/pages/pricing.md
TMK can you read this pricing page update and tell me what you think about it?
=> Add pricing to our documentation

sourcecode/hub/app/Http/Requests/ContentFilter.php, sourcecode/hub/tests/Browser/ContentTest.php
Addendum: changing the name of `$models` and `$model` in `ContentFilter::attachModel()` as this is ambiguous.
=> fix race condition between search and db

sourcecode/apis/contentauthor/resources/assets/react/theme/cerpusUI.js
Change of tab-color indicator for CA when editing H5Ps.
=> Change of tab-color indicator for CA when editing H5Ps.

sourcecode/hub/resources/views/components/content/action-buttons.blade.php, sourcecode/hub/tests/Browser/ContentTest.php
=> don't show use button without return url

sourcecode/apis/contentauthor/app/Http/Middleware/LtiAddToSession.php
=> restore "isAdmin" flag in session

sourcecode/hub/lang/en/messages.php, sourcecode/hub/lang/nb/messages.php, sourcecode/hub/lang/nn/messages.php, sourcecode/hub/resources/views/components/layout.blade.php
=> Changes to footer

sourcecode/apis/contentauthor/resources/assets/js/h5p-fixed-resize.js
Cannot reproduce locally, so no idea if this solves it.
=> attempt fixing race condition when exiting fullscreen
